[package]
name = "split-model-example"
version = "0.1.0"
edition = "2021"

[dependencies]
llama-cpp-4 = { path = "../../llama-cpp-4" }
anyhow = { workspace = true }
clap = { workspace = true, features = ["derive"] }
hf-hub = { workspace = true }