name: Publish to Crates.io

on:
  release:
    types:
      - created
    workflow_dispatch:

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955
        with:
          submodules: recursive
      - name: Publish crates for llama-cpp-sys-4
        run: RUST_BACKTRACE=1 cargo publish --package llama-cpp-sys-4 --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose 
      - name: Publish crates for llama-cpp-4
        run: RUST_BACKTRACE=1 cargo publish --package llama-cpp-4 --token ${{ secrets.CARGO_REGISTRY_TOKEN }} --verbose 
        
      # Trigger the 'update-toml-version' workflow
      - name: Dispatch Update TOML Version Event
        if: success()  # Ensure this runs only if the previous steps were successful
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.everest-preview+json" \
          "https://api.github.com/repos/${{ github.repository }}/dispatches" \
          -d '{"event_type": "trigger-update-toml-version"}'
